
name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Display Java version
      run: java -version

    - name: Build with Gradle
      run: ./gradlew build
      continue-on-error: true

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: app/build/outputs/apk/release/*.apk

    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: build/reports/
